/**
 * Kapurthala Online — Vendor Database
 * =====================================
 * HOW TO ADD / EDIT VENDORS:
 *   1. Copy an existing vendor object below
 *   2. Change the `id` to the next available number
 *   3. Fill in all fields
 *   4. Set `featured: true` for homepage spotlight
 *
 * CATEGORIES (use exact slug in vendor `category` field):
 *   grocery · electronics · clothing · restaurant · services · medical · hardware
 */

/* ─── Category Definitions ─────────────────────────── */
window.KO_CATEGORIES = [
  { slug: 'all',          label: 'All Shops',    icon: '🏪', color: '#E07B2A' },
  { slug: 'grocery',      label: 'Grocery',      icon: '🛒', color: '#2D7A4F' },
  { slug: 'electronics',  label: 'Electronics',  icon: '📱', color: '#1A5F7A' },
  { slug: 'clothing',     label: 'Clothing',     icon: '👗', color: '#8B3A8A' },
  { slug: 'restaurant',   label: 'Restaurant',   icon: '🍛', color: '#C9400A' },
  { slug: 'services',     label: 'Services',     icon: '🛠️', color: '#1A4A7A' },
  { slug: 'medical',      label: 'Medical',      icon: '💊', color: '#B5341A' },
  { slug: 'hardware',     label: 'Hardware',     icon: '🔩', color: '#7A5A1A' },
];

/* ─── Vendor Records ────────────────────────────────── */
window.KO_VENDORS_DEFAULT = [

  /* ══ GROCERY ══════════════════════════════════════ */
  {
    id: 1,
    name: 'Sharma Kirana Store',
    owner: 'Rajesh Sharma',
    phone: '9876543210',
    whatsapp: '919876543210',
    address: 'Main Market, Near Clock Tower, Kapurthala',
    category: 'grocery',
    description: 'Your neighbourhood kirana store since 1985. We stock fresh daily essentials, pulses, spices, snacks, and dairy products. Home delivery available within 3 km. Special discounts on bulk orders for households and businesses.',
    rating: 4.7,
    since: 1985,
    timings: 'Mon–Sun: 7 am – 9 pm',
    tags: ['Home Delivery', 'Daily Essentials', 'Bulk Orders'],
    featured: true,
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=600&q=80&auto=format',
    mapLink: 'https://maps.google.com/?q=Kapurthala+Main+Market',
  },
  {
    id: 2,
    name: 'Guru Nanak Provision Store',
    owner: 'Harminder Singh',
    phone: '9812345678',
    whatsapp: '919812345678',
    address: 'Railway Road, Near Bus Stand, Kapurthala',
    category: 'grocery',
    description: 'Premium grocery store with over 2,000 products including imported goods. Specialising in organic produce and health foods. Monthly ration packages for families at discounted rates.',
    rating: 4.5,
    since: 1998,
    timings: 'Mon–Sat: 8 am – 8:30 pm | Sun: 9 am – 6 pm',
    tags: ['Organic', 'Health Foods', 'Monthly Packages'],
    featured: false,
    image: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=600&q=80&auto=format',
    mapLink: 'https://maps.google.com/?q=Kapurthala+Railway+Road',
  },
  {
    id: 3,
    name: 'Fresh Valley General Store',
    owner: 'Sukhwinder Kaur',
    phone: '9988112233',
    whatsapp: '919988112233',
    address: 'Civil Lines, Sultanpur Road, Kapurthala',
    category: 'grocery',
    description: 'Supermarket experience with local warmth. We carry fresh fruits, vegetables, grains, and imported goods. First in Kapurthala to introduce eco-friendly packaging and carry bags.',
    rating: 4.6,
    since: 2010,
    timings: 'Mon–Sun: 8 am – 9 pm',
    tags: ['Eco-Friendly', 'Fresh Produce', 'Imported Goods'],
    featured: false,
    image: 'https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=600&q=80&auto=format',
    mapLink: 'https://maps.google.com/?q=Kapurthala+Civil+Lines',
  },

  /* ══ ELECTRONICS ══════════════════════════════════ */
  {
    id: 4,
    name: 'Sharma Electronics',
    owner: 'Rajiv Sharma',
    phone: '9988712345',
    whatsapp: '919988712345',
    address: 'Civil Lines, Near Jagatjit Palace, Kapurthala',
    category: 'electronics',
    description: 'Authorised dealer for Samsung, LG, and Sony. We sell mobile phones, TVs, refrigerators, and home appliances. Expert repair services with a 90-day warranty on all repairs performed.',
    rating: 4.6,
    since: 2005,
    timings: 'Mon–Sat: 10 am – 8 pm',
    tags: ['Authorised Dealer', 'Repairs', '90-Day Warranty'],
    featured: true,
    image: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=600&q=80&auto=format',
    mapLink: 'https://maps.google.com/?q=Kapurthala+Civil+Lines',
  },
  {
    id: 5,
    name: 'Digital World',
    owner: 'Amarjit Singh',
    phone: '9814567890',
    whatsapp: '919814567890',
    address: 'Kanjli Road, Near Government College, Kapurthala',
    category: 'electronics',
    description: "Kapurthala's largest laptop and computer store. New, refurbished, and custom-built PCs available. Data recovery, networking solutions, and CCTV camera installation also offered.",
    rating: 4.4,
    since: 2012,
    timings: 'Mon–Sat: 9:30 am – 7:30 pm',
    tags: ['Laptops', 'Data Recovery', 'CCTV', 'Networking'],
    featured: false,
    image: 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=600&q=80&auto=format',
    mapLink: 'https://maps.google.com/?q=Kapurthala+Kanjli+Road',
  },
  {
    id: 6,
    name: 'Mobile Zone',
    owner: 'Priya Arora',
    phone: '9876001122',
    whatsapp: '919876001122',
    address: 'Main Bazar, Near Moorish Mosque, Kapurthala',
    category: 'electronics',
    description: 'All mobile brands at best prices — iPhone, Samsung, Vivo, Oppo, Realme, and more. Accessories, cases, chargers, and screen protection film installed on the spot.',
    rating: 4.3,
    since: 2017,
    timings: 'Mon–Sun: 10 am – 9 pm',
    tags: ['All Brands', 'Accessories', 'Screen Guard'],
    featured: false,
    image: 'https://images.unsplash.com/photo-1556656793-08538906a9f8?w=600&q=80&auto=format',
    mapLink: 'https://maps.google.com/?q=Kapurthala+Main+Bazar',
  },

  /* ══ CLOTHING ══════════════════════════════════════ */
  {
    id: 7,
    name: 'Punjab Fashion House',
    owner: 'Manpreet Kaur',
    phone: '9775689012',
    whatsapp: '919775689012',
    address: 'Sultanpur Road, Near Bus Stand, Kapurthala',
    category: 'clothing',
    description: 'Designer ethnic wear for every occasion. Bridal lehengas, salwar kameez, sherwanis, and casual western wear. Custom stitching by experienced tailors. Collections refreshed every season.',
    rating: 4.8,
    since: 2010,
    timings: 'Mon–Sat: 10 am – 8 pm | Sun: 11 am – 6 pm',
    tags: ['Bridal Wear', 'Custom Stitching', 'Ethnic Wear'],
    featured: true,
    image: 'https://images.unsplash.com/photo-1603400521630-9f2de124b33b?w=600&q=80&auto=format',
    mapLink: 'https://maps.google.com/?q=Kapurthala+Sultanpur+Road',
  },
  {
    id: 8,
    name: 'Sartaj Readymade Garments',
    owner: 'Gurpreet Singh',
    phone: '9815223344',
    whatsapp: '919815223344',
    address: 'Ram Nagar, Main Market, Kapurthala',
    category: 'clothing',
    description: 'Readymade garments for men, women, and children. Affordable western and traditional clothing. School uniforms stitched to order. Bulk orders for events at special pricing.',
    rating: 4.2,
    since: 2003,
    timings: 'Mon–Sun: 9 am – 8 pm',
    tags: ['Readymade', 'Uniforms', 'Affordable', 'Bulk Orders'],
    featured: false,
    image: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=600&q=80&auto=format',
    mapLink: 'https://maps.google.com/?q=Kapurthala+Ram+Nagar',
  },
  {
    id: 9,
    name: 'Anmol Sarees',
    owner: 'Sunita Devi',
    phone: '9988334455',
    whatsapp: '919988334455',
    address: 'Kapurthala Chowk, Near Panch Mandir, Kapurthala',
    category: 'clothing',
    description: 'Curated collection of sarees from across India — Banarasi silk, Kanjeevaram, Chanderi, and cotton prints. Blouse stitching and draping service. Perfect for weddings and festivals.',
    rating: 4.6,
    since: 1995,
    timings: 'Tue–Sun: 10 am – 7 pm | Mon: Closed',
    tags: ['Silk Sarees', 'Blouse Stitching', 'Bridal', 'Festivals'],
    featured: false,
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&q=80&auto=format',
    mapLink: 'https://maps.google.com/?q=Kapurthala+Panch+Mandir',
  },

  /* ══ RESTAURANT ════════════════════════════════════ */
  {
    id: 10,
    name: 'Punjabi Dhaba No.1',
    owner: 'Balvinder Singh',
    phone: '9876554321',
    whatsapp: '919876554321',
    address: 'GT Road, Near Petrol Pump, Kapurthala',
    category: 'restaurant',
    description: 'Authentic Punjabi food cooked over a wood fire. Sarson da Saag, Makki di Roti, Dal Makhani, and Lassi are legendary. Open 24 hours — loved by locals and highway travellers alike.',
    rating: 4.9,
    since: 1978,
    timings: 'Open 24 Hours · 7 Days a Week',
    tags: ['24 Hours', 'Authentic Punjabi', 'Dal Makhani', 'Lassi'],
    featured: true,
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&q=80&auto=format',
    mapLink: 'https://maps.google.com/?q=Kapurthala+GT+Road',
  },
  {
    id: 11,
    name: 'Kapurthala Sweet House',
    owner: 'Jaswant Kumar',
    phone: '9814556677',
    whatsapp: '919814556677',
    address: 'Main Market, Near Clock Tower, Kapurthala',
    category: 'restaurant',
    description: 'Famous for fresh mithai, namkeen, and bakery items. Pinni, Gulab Jamun, Khoya Barfi, and Jalebi made fresh every morning. Catering available for weddings and events.',
    rating: 4.7,
    since: 1965,
    timings: 'Mon–Sun: 7 am – 9 pm',
    tags: ['Fresh Daily', 'Catering', 'Mithai', 'Bakery'],
    featured: true,
    image: 'https://images.unsplash.com/photo-1571506165871-ee72a35bc9d4?w=600&q=80&auto=format',
    mapLink: 'https://maps.google.com/?q=Kapurthala+Clock+Tower',
  },
  {
    id: 12,
    name: 'Green Garden Restaurant',
    owner: 'Rohit Verma',
    phone: '9988112200',
    whatsapp: '919988112200',
    address: 'Civil Lines, Near Sainik School Road, Kapurthala',
    category: 'restaurant',
    description: 'Family restaurant serving vegetarian Indian and Chinese cuisine. Air-conditioned seating for 80 guests. Birthday party packages and group bookings available. On Swiggy and Zomato.',
    rating: 4.3,
    since: 2014,
    timings: 'Mon–Sun: 11 am – 11 pm',
    tags: ['Family Dining', 'AC Seating', 'Delivery', 'Parties'],
    featured: false,
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80&auto=format',
    mapLink: 'https://maps.google.com/?q=Kapurthala+Civil+Lines',
  },

  /* ══ SERVICES ══════════════════════════════════════ */
  {
    id: 13,
    name: 'Kapurthala Print House',
    owner: 'Arjun Sharma',
    phone: '9876112233',
    whatsapp: '919876112233',
    address: 'Industrial Area, Near Govt School, Kapurthala',
    category: 'services',
    description: 'Complete printing solutions — visiting cards, banners, flex boards, wedding invitations, brochures, and ID cards. Digital and offset printing with same-day turnaround on standard orders.',
    rating: 4.5,
    since: 2008,
    timings: 'Mon–Sat: 9 am – 7 pm',
    tags: ['Same Day', 'Wedding Cards', 'Banners', 'Flex Boards'],
    featured: false,
    image: 'https://images.unsplash.com/photo-1562408590-e32931084e23?w=600&q=80&auto=format',
    mapLink: 'https://maps.google.com/?q=Kapurthala+Industrial+Area',
  },
  {
    id: 14,
    name: 'Fast Fix Repairs',
    owner: 'Vikram Singh',
    phone: '9815778899',
    whatsapp: '919815778899',
    address: 'Railway Road, Near Bus Stand, Kapurthala',
    category: 'services',
    description: 'Repair everything under one roof — mobile phones, laptops, TVs, refrigerators, and ACs. Pickup and drop service available. All repairs include a 6-month warranty. Open Sundays too.',
    rating: 4.4,
    since: 2015,
    timings: 'Mon–Sun: 9 am – 8 pm',
    tags: ['Pickup & Drop', '6-Month Warranty', 'All Repairs'],
    featured: false,
    image: 'https://images.unsplash.com/photo-1573152958734-1922c188fba3?w=600&q=80&auto=format',
    mapLink: 'https://maps.google.com/?q=Kapurthala+Railway+Road',
  },
  {
    id: 15,
    name: 'Bright Minds Academy',
    owner: 'Dr. Neha Gupta',
    phone: '9988667733',
    whatsapp: '919988667733',
    address: 'Civil Lines, Near DAV School, Kapurthala',
    category: 'services',
    description: 'Coaching centre for Classes 6–12. Subjects: Maths, Science, English, and Commerce. Dedicated JEE and NEET preparation batches. Small batch sizes for personal attention. Proven results.',
    rating: 4.8,
    since: 2011,
    timings: 'Mon–Sat: 7 am – 8 pm',
    tags: ['JEE', 'NEET', 'Classes 6–12', 'Small Batches'],
    featured: false,
    image: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=600&q=80&auto=format',
    mapLink: 'https://maps.google.com/?q=Kapurthala+Civil+Lines',
  },

  /* ══ MEDICAL ════════════════════════════════════════ */
  {
    id: 16,
    name: 'Kiran Medical Store',
    owner: 'Dr. Kiran Bhatia',
    phone: '9677022334',
    whatsapp: '919677022334',
    address: 'Near Civil Hospital, Hospital Road, Kapurthala',
    category: 'medical',
    description: 'Full range of allopathic, ayurvedic, and homeopathic medicines. Surgical equipment. Cosmetics and baby care products. Pharmacist on duty 24 hours. Free medicine delivery in Kapurthala city.',
    rating: 4.9,
    since: 2000,
    timings: 'Open 24 Hours · 7 Days a Week',
    tags: ['24 Hours', 'Free Delivery', 'Pharmacist On Duty'],
    featured: true,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80&auto=format',
    mapLink: 'https://maps.google.com/?q=Kapurthala+Civil+Hospital',
  },
  {
    id: 17,
    name: 'City Pharmacy',
    owner: 'Navdeep Singh',
    phone: '9815443322',
    whatsapp: '919815443322',
    address: 'Main Market, Kapurthala Chowk, Kapurthala',
    category: 'medical',
    description: 'Licensed pharmacy with 5,000+ medicines in stock. Doctor consultations by appointment. Diagnostic test sample collection service. Free blood pressure and sugar monitoring available daily.',
    rating: 4.5,
    since: 2007,
    timings: 'Mon–Sun: 8 am – 10 pm',
    tags: ['5000+ Medicines', 'Diagnostics', 'BP & Sugar Test'],
    featured: false,
    image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&q=80&auto=format',
    mapLink: 'https://maps.google.com/?q=Kapurthala+Chowk',
  },
  {
    id: 18,
    name: 'HealthCare Polyclinic',
    owner: 'Dr. Amandeep Kaur',
    phone: '9988444567',
    whatsapp: '919988444567',
    address: 'Kanjli Road, Near Central Park, Kapurthala',
    category: 'medical',
    description: 'Multi-speciality polyclinic: general medicine, gynaecology, paediatrics, and orthopaedics. In-house lab for blood tests. WhatsApp appointment booking available anytime.',
    rating: 4.7,
    since: 2016,
    timings: 'Mon–Sat: 9 am–2 pm, 5 pm–8 pm | Sun: 9 am–12 pm',
    tags: ['Multi-Speciality', 'In-House Lab', 'WhatsApp Booking'],
    featured: false,
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600&q=80&auto=format',
    mapLink: 'https://maps.google.com/?q=Kapurthala+Kanjli+Road',
  },

  /* ══ HARDWARE ══════════════════════════════════════ */
  {
    id: 19,
    name: 'Golden Hardware',
    owner: 'Harjit Bains',
    phone: '9814055566',
    whatsapp: '919814055566',
    address: 'Industrial Area, Near Bus Depot, Kapurthala',
    category: 'hardware',
    description: 'Complete hardware store — pipes, fittings, tools, paints, plumbing, and electrical supplies. Wholesale and retail. Trusted by contractors and builders across the district since 1998.',
    rating: 4.5,
    since: 1998,
    timings: 'Mon–Sat: 8 am – 7 pm',
    tags: ['Wholesale', 'Plumbing', 'Electrical', 'Paints'],
    featured: false,
    image: 'https://images.unsplash.com/photo-1530124566582-a618bc2615dc?w=600&q=80&auto=format',
    mapLink: 'https://maps.google.com/?q=Kapurthala+Industrial+Area',
  },
  {
    id: 20,
    name: 'Singh Building Materials',
    owner: 'Gurdeep Singh',
    phone: '9876998877',
    whatsapp: '919876998877',
    address: 'GT Road, Opposite Grain Market, Kapurthala',
    category: 'hardware',
    description: 'Bricks, cement, steel, tiles, and all construction materials. Free home delivery on bulk orders within 10 km. Free consultation for new construction projects. Preferred by local builders.',
    rating: 4.3,
    since: 2001,
    timings: 'Mon–Sat: 8 am – 7 pm | Sun: 9 am – 2 pm',
    tags: ['Cement', 'Steel', 'Tiles', 'Free Delivery'],
    featured: false,
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&q=80&auto=format',
    mapLink: 'https://maps.google.com/?q=Kapurthala+GT+Road',
  },
  {
    id: 21,
    name: 'Power Tools Plus',
    owner: 'Maninder Singh',
    phone: '9988221133',
    whatsapp: '919988221133',
    address: 'Near Railway Workshop, Phagwara Road, Kapurthala',
    category: 'hardware',
    description: 'Specialists in power tools, machinery, and safety equipment. Bosch, Makita, and DeWalt authorised dealer. Tool rental service available for short-term projects.',
    rating: 4.6,
    since: 2009,
    timings: 'Mon–Sat: 9 am – 6:30 pm',
    tags: ['Power Tools', 'Tool Rental', 'Bosch', 'Makita'],
    featured: false,
    image: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=600&q=80&auto=format',
    mapLink: 'https://maps.google.com/?q=Kapurthala+Phagwara+Road',
  },
];
